spring.application.name=shadow-exchange

spring.datasource.url=jdbc:postgresql://localhost:5432/shadow_exchange
spring.datasource.username=shadow
spring.datasource.password=shadow123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

